# Generated by Django 4.2.6 on 2023-12-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="join",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("applications_name", models.CharField(max_length=10)),
                ("apllications_studentID", models.IntegerField(default=0)),
                ("applications_phoneNumber", models.IntegerField(default=-6912)),
                ("applications_text", models.TextField()),
            ],
        ),
    ]
